apiVersion: v1
kind: Secret
metadata:
  name: ordering-system-secrets
type: Opaque
stringData:
  postgres-connection: "Host=postgres;Database=OrderingDb;Username=postgres;Password=P@ssw0rd123"
  postgres-password: "P@ssw0rd123"
  rabbitmq-password: "Ordering2026"
  openai-key: "ollama-local"