services:
  # 1. Database
  postgres-db:
    image: postgres:latest
    container_name: ordering-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: OrderingDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # 2. Redis (Replaces Azure Cache for Redis)
  redis-cache:
    image: redis:latest
    container_name: ordering-redis
    ports:
      - "6379:6379"

  # 3. RabbitMQ (Replaces Azure Service Bus)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ordering-rabbitmq
    ports:
      - "5672:5672"   # App connection
      - "15672:15672" # Management Dashboard
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  # 4. LLM Worker Service
  ordering-worker:
    container_name: ordering-worker
    build:
      context: .
      dockerfile: Worker.Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=OrderingDb;Username=postgres;Password=P@ssw0rd123
      - Ollama__Endpoint=http://host.docker.internal:11434
      - MessageBroker__Host=rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Teaches native Linux Docker to resolve this domain to 172.17.0.1 automatically!
    depends_on:
      postgres-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - default

  # 5. Api
  ordering-api:
    container_name: ordering-api
    build:
      context: .
      dockerfile: API.Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=OrderingDb;Username=postgres;Password=P@ssw0rd123
      
      # Hardened Configuration Binding Formats for RabbitMQ Connection
      - MessageBroker__Host=rabbitmq
      - MessageBroker__Username=guest
      - MessageBroker__Password=guest
      
      - MessageBroker_Host=rabbitmq
      - MessageBroker_Username=guest
      - MessageBroker_Password=guest
      
      - "MessageBroker:Host=rabbitmq"
      - "MessageBroker:Username=guest"
      - "MessageBroker:Password=guest"
      
      - ConnectionStrings__Redis=redis-cache:6379
    depends_on:
      postgres-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  postgres_data: