apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-staging-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-staging
  template:
    metadata:
      labels:
        app: postgres-staging
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: OrderingDb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "StagingSuperPassword123" # Matches your staging secret!
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-staging-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-staging-storage
        persistentVolumeClaim:
          claimName: postgres-staging-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rbd-postgres-staging                  # Matches your connection string host!
  namespace: staging
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-staging