apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-worker-config
  namespace: staging
data:
  MessageBroker__Host: "rabbitmq-staging-service"
  #Ollama__Endpoint: "http://ollama-wsl-bridge:11434/v1"
  #Ollama__Endpoint: "http://host.docker.internal:11434/v1"
  Ollama__Endpoint: "http://ollama-wsl-bridge.staging.svc.cluster.local:11434/v1/"
  Ollama__Model: "llama3"
