apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordering-api
  namespace: staging
  labels:
    app: ordering-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordering-api
  template:
    metadata:
      labels:
        app: ordering-api
    spec:
      containers:
      - name: ordering-api
        image: local-registry/ordering-api:v24
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: RedisSettings__IsEnabled
          value: "false"
        - name: ConnectionStrings__Redis
          value: "localhost:6379,abortConnect=false"
        - name: MessageBroker__Host
          value: "rabbitmq-staging-service.staging.svc.cluster.local"
        - name: MessageBroker__Port
          value: "5672"
        - name: MessageBroker__Username
          value: "guest"
        - name: MessageBroker__Password
          value: "StagingRabbitPassword123"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=rbd-postgres-staging;Database=OrderingDb;Username=postgres;Password=StagingSuperPassword123"
        - name: ConnectionStrings__OrderingDb
          value: "Host=rbd-postgres-staging;Database=OrderingDb;Username=postgres;Password=StagingSuperPassword123"
---
apiVersion: v1
kind: Service
metadata:
  name: ordering-api
  namespace: staging
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ordering-api