apiVersion: batch/v1
kind: Job
metadata:
  name: ordering-db-migration
  namespace: staging
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  template:
    metadata:
      name: ordering-db-migration
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: migration-runner
        image: ghcr.io/centallas/orderingsystem-cleanarch-worker:staging
        imagePullPolicy: Always
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=rbd-postgres-staging;Database=OrderingDbStaging;Username=postgres;Password=postgres"
      restartPolicy: OnFailure
  backoffLimit: 2