apiVersion: batch/v1
kind: Job
metadata:
  name: ordering-db-migration
  namespace: staging
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: ordering-db-migration
    spec:
      containers:
      - name: migration-runner
        image: ghcr.io/centallas/orderingsystem-cleanarch-worker:staging
        imagePullPolicy: Always
        command: ["dotnet", "ef", "database", "update"]
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=rbd-postgres-staging;Database=OrderingDb;Username=postgres;Password=StagingSuperPassword123;"
      restartPolicy: OnFailure
  backoffLimit: 3